### ISSUE TITLE
NAIST数学問題&解答2018入学者用.pdf

### ISSUE THREAD

**Issue by gaheek-rl** [tubutubucorn/naist-exam#1]
間違いかもしれませんが
NAIST数学問題&解答2018入学者用.pdfの一番最初の問題は
lambdaによって場合分けが必要だと思います.
lambdaが0以上の場合は、p(x)の面積は0か発散してしまいます.

問題のアップロードありがとうございます！
とても助かりました！

**Comment by gaheek-rl** [comment]
勘違いでしたらすみません！

**Comment by freddy5566** [comment]
It should've been exp(negative lambda x). In this case, the answer would be 1/lambda.
